version: '3.8'
services:
  app:
    container_name: recipe_cat
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_PASSWORD: dev
      DB_USER: dev
      DB_NAME: dev
      DB_HOST: primary_postgres
    tty: true
    volumes:
      - .:/opt
    ports:
      - '8000:8000'
    depends_on:
      - primary_postgres

  primary_postgres:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5442:5432'
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev

volumes:
  postgres_data: