version: '3.8'
services:
  app:
    container_name: recipe_cat
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_PASSWORD: dev
      DB_USER: dev
      DB_NAME: dev
      DB_HOST: primary_postgres
    tty: true
    volumes:
      - ./:/opt/app/
    ports:
      - '8002:8002'
  primary_postgres:
    image: postgres:15.1
    ports:
      - '5442:5432'
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev
